name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  zip-folder:
    runs-on: ubuntu-latest
    steps:
      # - uses: montudor/action-zip@v1
      - run: ls ${{ github.workspace }}
